# Generated by Django 3.2.9 on 2022-05-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPremiumArticle',
            fields=[
            ],
            options={
                'verbose_name': 'Non-premium article',
                'verbose_name_plural': 'Non-premium articles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.article',),
        ),
        migrations.CreateModel(
            name='NonSubmitedArticle',
            fields=[
            ],
            options={
                'verbose_name': 'Non-submited article',
                'verbose_name_plural': 'Non-submited articles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.article',),
        ),
        migrations.CreateModel(
            name='PremiumArticle',
            fields=[
            ],
            options={
                'verbose_name': 'Premium article',
                'verbose_name_plural': 'Premium articles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.article',),
        ),
        migrations.CreateModel(
            name='PrivateArticle',
            fields=[
            ],
            options={
                'verbose_name': 'Private article',
                'verbose_name_plural': 'Private articles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.article',),
        ),
        migrations.CreateModel(
            name='PublicArticle',
            fields=[
            ],
            options={
                'verbose_name': 'Public article',
                'verbose_name_plural': 'Public articles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.article',),
        ),
        migrations.CreateModel(
            name='SubmitedArticle',
            fields=[
            ],
            options={
                'verbose_name': 'Submited article',
                'verbose_name_plural': 'Submited articles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.article',),
        ),
    ]
