# Generated by Django 3.2.9 on 2022-05-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_nonpremiumarticle_nonsubmitedarticle_premiumarticle_privatearticle_publicarticle_submitedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='full_url',
            field=models.CharField(blank=True, default='No URL', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default='No author', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='picture_url',
            field=models.CharField(blank=True, default='No picture', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, default='No title', max_length=5000, null=True),
        ),
    ]
