# Generated by Django 3.2.9 on 2022-05-23 19:02

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('version', models.CharField(default='1.0', max_length=4)),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('summary', models.TextField(max_length=150)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API Documentation',
                'verbose_name_plural': 'API Documentations',
                'ordering': ['-date', 'is_public'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('undefined', 'Undefined')], default='undefined', max_length=10)),
                ('api_key', models.CharField(editable=False, max_length=200, unique=True)),
                ('hashed_api_key', models.CharField(editable=False, max_length=200, unique=True)),
                ('extra_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'age'],
            },
        ),
    ]
