# Generated by Django 3.2.9 on 2022-05-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPremiumReceipe',
            fields=[
            ],
            options={
                'verbose_name': 'Non-premium Receipe',
                'verbose_name_plural': 'Non-premium Receipes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('receipes.receipe',),
        ),
        migrations.CreateModel(
            name='NonSubmitedReceipe',
            fields=[
            ],
            options={
                'verbose_name': 'Non-submited Receipe',
                'verbose_name_plural': 'Non-submited Receipes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('receipes.receipe',),
        ),
        migrations.CreateModel(
            name='PremiumReceipe',
            fields=[
            ],
            options={
                'verbose_name': 'Premium Receipe',
                'verbose_name_plural': 'Premium Receipes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('receipes.receipe',),
        ),
        migrations.CreateModel(
            name='PrivateReceipe',
            fields=[
            ],
            options={
                'verbose_name': 'Private Receipe',
                'verbose_name_plural': 'Private Receipes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('receipes.receipe',),
        ),
        migrations.CreateModel(
            name='PublicReceipe',
            fields=[
            ],
            options={
                'verbose_name': 'Public Receipe',
                'verbose_name_plural': 'Public Receipes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('receipes.receipe',),
        ),
        migrations.CreateModel(
            name='SubmitedReceipe',
            fields=[
            ],
            options={
                'verbose_name': 'Submited Receipe',
                'verbose_name_plural': 'Submited Receipes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('receipes.receipe',),
        ),
        migrations.RemoveField(
            model_name='cuisine',
            name='submited_by',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='submited_by',
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
