# Generated by Django 3.2.9 on 2022-05-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipes', '0002_auto_20220525_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='tags',
        ),
    ]
